### ISSUE TITLE
/functions directory in root does not work

### ISSUE THREAD

**Issue by fineshop** [cloudflare/next-on-pages#108]
As per docs on [Cloudflare Pages](https://developers.cloudflare.com/pages/platform/functions/get-started), I tried adding a /functions/hello.ts file in my project but when I visit /hello, it shows error page.

**Comment by dario-piotrowicz** [comment]
Hi @fineshop what you linked is the documentation for generic Pages Functions, if you are working on a next-on-pages project you should not use Pages Functions but Next [api routes](https://nextjs.org/docs/api-routes/introduction) instead (or more specifically edge api routes as we mention in our [nextjs guide](https://nextjs.org/docs/api-routes/introduction)).

I hope this helps, if it does please let me know so that I can close this issue, if doesn't feel free to provide more details so I can try to assist further 🙂

**Comment by dario-piotrowicz** [comment]
Yes, you can use [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites) to map `/users` to `/api/users` (in this way both `/users` and `/api/users` will return the same but I am not sure if you can prevent `/api/users` to respond, I guess it'd need a bit of playing around)

But unfortunately it doesn't look like next-on-pages supports rewrites at the moment, I'll create an issue for that.

**Comment by dario-piotrowicz** [comment]
Closing this issue as I think it's not applicable / resolved

**Comment by brianfryer** [comment]
@dario-piotrowicz how would you go about configuring a codebase so that the `/functions` directory at the root of the project can be used in tandem with `@cloudflare/next-on-pages`? 

I need to be able to deploy a non-edge function alongside the edge functions that are automatically generated by `@cloudflare/next-on-pages`.

**Comment by dario-piotrowicz** [comment]
Pages isn't well positioned to do that unfortunately, I was chatting with @GregBrimble today and he has plans to make Pages more flexible in the future so that what you're asking would be really simple to implement 😓 (he's started with this PR but it doesn't look like things are going to progress any time soon unfortunately: https://github.com/cloudflare/workers-sdk/pull/1740)

Right now... I am not really sure, you could make your repo a monorepo and have two different pages applications one with `/functions` and one with the next-on-pages app?

Anyways could you give me more details? what are you trying to accomplish and why aren't Next api routes enough? maybe there is something that can be done without using `/functions`?
