### ISSUE TITLE
Does WebSocket possible??

### ISSUE THREAD

**Issue by zizifn** [cloudflare/next-on-pages#131]
I know next.js edge does not support WebSocket, but does this possible to use WebSocket in next on pages??

**Comment by zizifn** [comment]
can be, but the type will has issues. Use any pass the typescript error..

**Comment by dario-piotrowicz** [comment]
@zizifn sorry for the later reply I wanted to find some time to have a quick play with it before commenting :bow: 
(and just as I was about to put my comment here I noticed that you've closed the issue :cry:)

I got something working: https://next-app-websocket-pages.pages.dev/
please have a look at the app and let me know if that's the sort of thing you were thinking of, the code is in this [repo](https://github.com/dario-piotrowicz/next-app-websocket-pages).

As types go I think it's actually all good (since I'm using [`@cloudflare/workers-types`](https://www.npmjs.com/package/@cloudflare/workers-types)), the biggest issue that I've found here is that the websocket doesn't seem to be working locally :confused:

**Comment by zizifn** [comment]
> @zizifn sorry for the later reply I wanted to find some time to have a quick play with it before commenting 🙇 (and just as I was about to put my comment here I noticed that you've closed the issue 😢)
> 
> I got something working: https://next-app-websocket-pages.pages.dev/ please have a look at the app and let me know if that's the sort of thing you were thinking of, the code is in this [repo](https://github.com/dario-piotrowicz/next-app-websocket-pages).
> 
> As types go I think it's actually all good (since I'm using [`@cloudflare/workers-types`](https://www.npmjs.com/package/@cloudflare/workers-types)), the biggest issue that I've found here is that the websocket doesn't seem to be working locally 😕

Thanks, I didn't try in locally for now, will try later..  

I saw you use `(server as WebSocket & { accept: () => void }).accept();` to bypass `WebSocket ` don't has `accept` method..
I use `any` in my repo https://github.com/zizifn/myTrash/blob/main/src/app/api/ws/route.ts#L14

**Comment by dario-piotrowicz** [comment]
> I saw you use (server as WebSocket & { accept: () => void }).accept(); to bypass WebSocket  don't has accept method..
ah yeah sorry I forgot about that one :sweat:

**Comment by zizifn** [comment]
> > I saw you use (server as WebSocket & { accept: () => void }).accept(); to bypass WebSocket  don't has accept method..
> > ah yeah sorry I forgot about that one 😓

Thanks! I will try websocket locally when I have time, will let you know the result...

**Comment by zizifn** [comment]
> > > I saw you use (server as WebSocket & { accept: () => void }).accept(); to bypass WebSocket  don't has accept method..
> > > ah yeah sorry I forgot about that one 😓
> 
> Thanks! I will try websocket locally when I have time, will let you know the result...

My [repo ](https://github.com/zizifn/myTrash) is working with with GitHub codespace..
![image](https://user-images.githubusercontent.com/1803942/230761816-fa4e3f18-a7a5-4135-b3e0-1595339b5e1b.png)
