### ISSUE TITLE
Built-in i18n Next JS can not run on CloudFlare Pages after deployment

### ISSUE THREAD

**Issue by ThuKieuIC2** [cloudflare/next-on-pages#132]
Hello All,

I am building a simple company site: Next JS 13, i18n built-in for both English and Vietnamese:
i18n: {
    locales: ['vi',  'en'],
    defaultLocale: 'vi'
  },
Vercel builds, deploys and runs NextJs i18n built-in smoothly, and it points/routes to default locale correctly without adding /vi in URL. 
However, move on CloudFlare Pages is not good on running the result.

Root cause:
- CF Pages builds Vercel output containing static for both en and vi locale files
- CF Pages server points the default locale domain (e.g ax89.pages.dev) to index file, not en or vi files
- Only work if URL contains locale path: https://ax89.pages.dev/vi or https://ax89.pages.dev/en
Please help.
NOTE: the sample URL above it is for explaination only.

**Comment by james-elicx** [comment]
It appears that i18n relies on redirects and rewrites that take place in the routing system that we implement, and utilises header and cookie checks in this process.

This functionality is not currently implemented but is a work in progress, per the new routing system detailed in #129.

**Comment by ThuKieuIC2** [comment]
I think that Cloudflare can solve this some ways:
(i) Next-on-Pages code should Build a template of index.js/index.html and point to the default locale file => fastest way
(ii) Pages Server opens a setting for locale routing/redirect => Slowest due to CF global infrastructure 
- By Header
- By Customer domain with additional locale ending paths

For my company, I will try will i18n by Domain in next.config.js but this is not flexible in CI/CD env over Preview, Product and customer domains vs Pages auto-gen domain.

**Comment by dario-piotrowicz** [comment]
@ThuKieuIC2 we might end up not supporting the built-in I18n (see: https://github.com/cloudflare/next-on-pages/issues/129#issuecomment-1494983278), could you implement your application using something like [next-intl](https://next-intl-docs.vercel.app/) instead?

**Comment by ThuKieuIC2** [comment]
Thank you @dario-piotrowicz I **solved** by this manual step:
(i) Keep next.config.js
```
i18n: {
    locales: ['vi',  'en'],
    defaultLocale: 'vi',
    localeDetection: false,
  },
```
(ii) Add this line to public/_redirects
```
/ /vi 301
```

**Comment by dario-piotrowicz** [comment]
Ah ok, thank you very much @ThuKieuIC2 😃 🎉 

We'll probably want to document this workaround somewhere (probably in the [supported md](https://github.com/cloudflare/next-on-pages/blob/main/docs/supported.md)), I can do that 🙂👍

**Comment by ThuKieuIC2** [comment]
@TheAxZim I have some approach, we can try:
1. Keep _redirects with 1st default locale routing (this fix CF Pages servers :) ) . Then you can control redirect/re-route again by the detected language (end-user browser). End-user see the fixed locale page before go to her/his locale page.

2. Remove all routing in _redirects and _headers; create /public/index.html file then add javascript code to detect locale and call redirect from browser. Ref: [1](https://gist.github.com/bvandenbon/dae62a7008d34ab0895e42d9dc5131fa)

You can see pros and cons of both way :) but it should work because we both fix CF Pages servers and end-user browser.

**Comment by HakanSungur** [comment]
Sorry to comment on a closed topic but I need your help as your problem is similar to mine. I am trying to deploy Next js 14 to cloudflare workers. When I run npm run preview:worker I see that routes are not automatically created.
I saw that it was domain.com/tr, but it was replaced with domain.com.
**i18n/client.js**
`'use client'

import i18next from 'i18next'
import { useEffect, useState } from 'react'
import { initReactI18next, useTranslation as useTranslationOrg } from 'react-i18next'
import { useCookies } from 'react-cookie'
import resourcesToBackend from 'i18next-resources-to-backend'
import LanguageDetector from 'i18next-browser-languagedetector'
import { getOptions, languages, cookieName } from './settings'

const runsOnServerSide = typeof window === 'undefined'
i18next
  .use(initReactI18next)
  .use(LanguageDetector)
  .use(resourcesToBackend((language, namespace) => import(`./locales/${language}/${namespace}.json`)))
  // .use(LocizeBackend) // locize backend could be used on client side, but prefer to keep it in sync with server side
  .init({
    ...getOptions(),
    lng: undefined, // let detect the language on client side
    detection: {
      order: ['path', 'htmlTag', 'cookie', 'navigator'],
    },
    preload: runsOnServerSide ? languages : []
  })

export function useTranslation(lng, ns, options) {
  const [cookies, setCookie] = useCookies([cookieName])
  const ret = useTranslationOrg(ns, options)
  const { i18n } = ret
  if (runsOnServerSide && lng && i18n.resolvedLanguage !== lng) {
    i18n.changeLanguage(lng)
  } else {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [activeLng, setActiveLng] = useState(i18n.resolvedLanguage)
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
      if (activeLng === i18n.resolvedLanguage) return
      setActiveLng(i18n.resolvedLanguage)
    }, [activeLng, i18n.resolvedLanguage])
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
      if (!lng || i18n.resolvedLanguage === lng) return
      i18n.changeLanguage(lng)
    }, [lng, i18n])
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
      if (cookies.i18next === lng) return
      setCookie(cookieName, lng, { path: '/' })
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [lng, cookies.i18next])
  }
  return ret
}

`
**i18n/index.js**
`import { createInstance } from 'i18next'
import resourcesToBackend from 'i18next-resources-to-backend'
import { initReactI18next } from 'react-i18next/initReactI18next'
import { getOptions } from './settings'

const initI18next = async (lng, ns) => {
  // on server side we create a new instance for each render, because during compilation everything seems to be executed in parallel
  const i18nInstance = createInstance()
  await i18nInstance
    .use(initReactI18next)
    .use(resourcesToBackend((language, namespace) => import(`./locales/${language}/${namespace}.json`)))
    .init(getOptions(lng, ns))
  return i18nInstance
}

export async function vacbidTranslation(lng, ns, options = {}) {
  const i18nextInstance = await initI18next(lng, ns)
  return {
    t: i18nextInstance.getFixedT(lng, Array.isArray(ns) ? ns[0] : ns, options.keyPrefix),
    i18n: i18nextInstance
  }
}`

**i18n/settigs.js**
`export const fallbackLng = 'en'
export const languages = [fallbackLng,"af","af-NA","af-ZA","an","ar","ar-AE","ar-AR","ar-BH","ar-DZ","ar-EG","ar-IQ","ar-KW","ar-LB",
"ar-LY","ar-MA","ar-OM","ar-QA","ar-SA","ar-SY","ar-TN","ar-YE","as","as-IN","az","az-AZ","be","be-BE","bg","bg-BG",
"bn","bn-BN","bs","bs-BA","ca","ca-ES","ch","co","cs","cs-CZ","da","da-DK","de","de-AT",
"de-CH","de-DE","de-LI","de-LU","el","el-GR","en-AE","en-AU","en-BZ","en-CA","en-GB","en-GY","en-IE",
"en-IN","en-JM","en-NZ","en-PH","en-SG","en-TT","en-US","en-ZA","en-ZW","eo","es","es-AR","es-BO",
"es-BZ","es-CL","es-CO","es-CR","es-DO","es-EC","es-ES","es-GT","es-HN","es-MX","es-NI","es-PA","es-PE","es-PR",
"es-PY","es-SV","es-US","es-UY","es-VE","et","eu","fa","fa-IR","fi","fi-FI","fj","fr","fr-BE","fr-CA","fr-CH",
"fr-FR","fr-LU","fr-MC","fy","ga","ga-IE","gd","gd-IE","gl","gu","he","he-IL","hi","hi-IN","hr","hr-HR","ht",
"hu","hu-HU","hy","hy-AM","id","id-ID","is","is-IS","it","it-CH","it-IT","it-LT","ja","ja-JP","ka","ka-GE",
"kk","km","kn","ko","ko-KP","ko-KR","ky","la","lb","lt","lv","lv-LV","mk","mk-MK","ml","ms","ms-MY",
"mt","mt-MT","nb","nl","nl-BE","nl-NL","nn","no","no-NO","or","pa","pa-IN","pl",
"pl-PL","pt","pt-AO","pt-BR","pt-PT","rm","ro","ro-MO","ro-RO","ru","ru-MO","ru-RU","sa","sc",
"sk","sk-SK","sl","sl-SI","sq","sq-AL","sr","sr-RS","sv","sv-FI","sv-SE","sv-SV","sw","te","th","th-TH",
"tr","tr-TR","uk","uk-UA","ur","vi","vi-VN","zh","zh-CH","zh-HK",
"zh-SG","zh-TW","zh-US","zh-CN","zu","zu-ZA"
];
export const defaultNS = 'translation'
export const cookieName = 'i18next'

export function getOptions (lng = fallbackLng, ns = defaultNS) {
  return {
    // debug: true,
    supportedLngs: languages,
    // preload: languages,
    fallbackLng,
    lng,
    fallbackNS: defaultNS,
    defaultNS,
    ns,
    // backend: {
    //   projectId: '01b2e5e8-6243-47d1-b36f-963dbb8bcae3'
    // }
  }
}
`
**public/_redirects**
`/* /index.html 200`

I can't figure it out, I really need your help.
