### ISSUE TITLE
[🐛 Bug]: Nextra i18n Build Does Not Show Anything

### ISSUE THREAD

**Issue by anaclumos** [cloudflare/next-on-pages#157]
### Cli version

0.7.0

### Next.js related information

13.2.4

### Vercel version

28.18.3

### Description

Nextra will success compiling, but will return an empty html.

### Reproduction

github.com/shuding/nextra

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @anaclumos thanks for the issue :slightly_smiling_face: 

I've tried making a simple nextra app and it does seem to look fine as you can see [here](https://my-nextra-app.pages.dev/) ([source code](https://github.com/dario-piotrowicz/my-nextra-app))

So I am wondering why it doesn't work for your app. Maybe you're using some Nextra features that are breaking it? (my app is very very simple as you can see)

Anyways if you want to explore and help fixing the issue you're encountering you're more than welcome to do so, please let me know if you need any assistance :slightly_smiling_face: (I am planning to soon add playground features to help develop and test the package locally, alongside a helpful guide, sorry that's still not in place)

**Comment by anaclumos** [comment]
I am using Nextra i18n. I think that may be the one breaking things, will have to check soon.

**Comment by anaclumos** [comment]
Also. Are you using Next.js Static Export? Next i18n does not support static exporting 😥

**Comment by james-elicx** [comment]
> I am using Nextra i18n. I think that may be the one breaking things, will have to check soon.

The `i18n` option in `next.config.js` is not currently supported by next-on-pages because of how routing is implemented. It's possible that it may be supported in the future, but it's worth noting that Next.js is [trying](https://beta.nextjs.org/docs/guides/internationalization) to move away from that configuration option with the new app directory.

I suspect that this may be why you aren't seeing anything when running your app.

Someone wrote some workarounds in #132, although I'm of the opinion that those just remove the Next.js internationalization support completely and won't work with the new routing system outlined in #129.

**Comment by dario-piotrowicz** [comment]
@anaclumos , we've just merged a PR @james-elicx made that should have fixed this issue, if you want please have a look using our latest beta version: https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-86df485 to see if everything works as expected for you now :slightly_smiling_face: :pray:
