### ISSUE TITLE
[⚡ Feature]: Nextjs under PNPM monorepo

### ISSUE THREAD

**Issue by tuahear** [cloudflare/next-on-pages#307]
### Description

My goal is to pass `cmd` option to `vercel build` command that's being used under the hood in order to specify my nextjs app directory that lives in the subfolder of a monorepo project.

Since [next-on-pages](https://github.com/cloudflare/next-on-pages) internally uses `pnpx vercel build` command. Is it possible to config or pass along additional options (https://vercel.com/docs/cli/build#global-options) to that command?

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by dario-piotrowicz** [comment]
Could you share the structure of your monorepo and what kind of behaviour you're looking for?

I am really wondering if there isn't a simpler/native way to accomplish what you want 🤔

**Comment by tuahear** [comment]
@dario-piotrowicz Thanks, my bad, yeah I meant `cwd`

So my monorepo is a pnpm repo in which a nextjs project lives inside 2 directories down the tree.

/
    /apps
          /nextjs-project <--- here
    /libs
/pnpm-lock.yaml

In order to let cloudflare build system (v2 beta) detect that my repo is a pnpm. I had to set `Root Directory` under the build configurations to be `/` so that it would see my `pnpm-lock.yaml` and use `pnpm install` accordingly.

Since root directory has to be `/`, I need a way to instruct this library, when building nextjs project, know where to look for the project (that is not the root directory). Though, passing `cwd` might not be the best idea as it might cause other side effects / issues. Do you have any better alternative in mind?

**Comment by luanmm** [comment]
I'm having the same problem, actually. In my scenario, I have 3 apps in a monorepo. Each one is published separately in a domain/path. I think I can manage the other "custom" aspects from my project, but the way Cloudflare published nowadays is really a problem.

PNPM detection strategy is a problem for me too, for the same reasons as reported by @tuahear. I don't think that detecting `pnpm-lock.yaml` inside the configured `Root Directory` is the best way to go. PNPM and Yarn supports "workspaces" out-of-the-box, so not in every case you will have a `pnpm-lock.yaml` in the **project's directory** (it will be in the **workspace** directory sometimes, which is our case here). So, when the "right" `Root Directory` for the project is specified, Cloudflare build process can't detect PNPM and it tries to use NPM as default package manager.

Secondly, if anyone can make more clear what Cloudflare expects to have in the output directory to handle Next.JS dynamic pages, I will appreciate. As I've seen, Next.JS just generates (in my project at least, configured with `output: standalone`) a "main" `server.js` file, that I would pass into a starting command like `node server.js` for instance. There are anything else that we may have to work with Cloudflare Pages? I may use just the edge runtime, if needed (this is not a problem in my case, I think). I just cannot publish the project as static because of a rewriting middleware and dynamic cache (or data retrieval).

Thanks in advance for all the attention regarding this issue! And congratulations for all Cloudflare team for the efforts to bring new pieces of technology and solutions to the table! Best regards!

**Comment by dario-piotrowicz** [comment]
@tuahear 
sorry for the late reply 🙇 

Please have a look at this example repo I made: https://github.com/dario-piotrowicz/simple-pnpm-next-on-pages-app-monorepo-example

It follows the structure you mentioned above and to integrate it with Pages you simply need to set the proper build command and output directory:
![Screenshot 2023-08-03 at 14 18 11](https://github.com/cloudflare/next-on-pages/assets/61631103/66d230ca-25b3-43cc-b6b6-406239e56408)

> **Note**
> I can appreciate that in my simple example you don't have extra libraries present, if you do (and they are dependencies of your nextjs-project) then you'd need to build them first, you could do that by properly tweaking the build script or by using monorepo tools such as Nx or turborepo

would a setup similar to this not work in your project?

**Comment by dario-piotrowicz** [comment]
@luanmm thanks for the comment (and congratulations 😄) 🙂

see my replies below

___

> I'm having the same problem, actually. In my scenario, I have 3 apps in a monorepo. Each one is published separately in a domain/path. I think I can manage the other "custom" aspects from my project, but the way Cloudflare published nowadays is really a problem.

For this I would suggest the same as above, set up a proper build command and output directory for your nextjs application.

But there's also the extra issue that Cloudflare Pages doesn't have support for repos with multiple applications so if you need to deploy more than one of those, you'll need to manually deploy them using wrangler (integrating it with GitHGub actions is quite straightforward with our [Pages Actions](https://github.com/cloudflare/pages-action), but you can have much more complex and custom behaviors, for example I have a [GitHub action](https://github.com/dario-piotrowicz/next-apps-for-testing/blob/master/.github/workflows/deploy.yml) that can deploy more than 10 next-on-pages applications from a single pnpm workspace monorepo)

> PNPM detection strategy is a problem for me too, for the same reasons as reported by @tuahear. I don't think that detecting pnpm-lock.yaml inside the configured Root Directory is the best way to go. PNPM and Yarn supports "workspaces" out-of-the-box, so not in every case you will have a pnpm-lock.yaml in the project's directory (it will be in the workspace directory sometimes, which is our case here). So, when the "right" Root Directory for the project is specified, Cloudflare build process can't detect PNPM and it tries to use NPM as default package manager.

with PNPM detection, I assume that you mean how `@cloudflare/next-on-pages` detects what package manager is currently in use right?
right now if you run the command in a sub-directory which doesn't contain the pnpm-lock.yaml file, we do indeed assume that pnpm is not being used instead of making sure that we are in a workspace, that's indeed a bug that's been on my radar (which also causes issues such as #401), I'll look into implementing a solution for it in the next few days (it should be pretty straightforward) 👍

> Secondly, if anyone can make more clear what Cloudflare expects to have in the output directory to handle Next.JS dynamic pages, I will appreciate. As I've seen, Next.JS just generates (in my project at least, configured with output: standalone) a "main" server.js file, that I would pass into a starting command like node server.js for instance. There are anything else that we may have to work with Cloudflare Pages? I may use just the edge runtime, if needed (this is not a problem in my case, I think). I just cannot publish the project as static because of a rewriting middleware and dynamic cache (or data retrieval).

The output directory expected to handle a Next.js application (besides building the application as static and just deploy it as such) is a directory looking like this:
![Screenshot 2023-08-03 at 14 47 57](https://github.com/cloudflare/next-on-pages/assets/61631103/5e280f19-3b86-4622-959d-6b3dcc4c6e6a)

The `standalone` output is not supported, you'll need to remove it in order to be able to use `@cloudflare/next-on-pages`, if you want you can use our [eslint-plugin](https://www.npmjs.com/package/eslint-plugin-next-on-pages) to help you working with the adapter, with the plugin you would have been warned about the output configuration not being supported:
![Screenshot 2023-08-03 at 14 58 22](https://github.com/cloudflare/next-on-pages/assets/61631103/69532d54-bbef-4cbe-82a0-edef4556530a)

___

I hope the above helps 🙂

**Comment by luanmm** [comment]
Thank you very much, @dario-piotrowicz! It is more clear now some of the mistakes I made while trying to run my project on Cloudflare Pages.

I tried to advance here and seems to be better than before, but this is the problem now:

```sh
...
▲  Build Completed in .vercel/output [25s]
⚡️ Completed `pnpm dlx vercel build`.

⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
⚡️ 
⚡️      The following routes were not configured to run with the Edge Runtime:
⚡️        - /_error
⚡️ 
⚡️      Please make sure that all your non-static routes export the following edge runtime route segment config:
⚡️        export const runtime = 'edge';
⚡️ 
⚡️      You can read more about the Edge Runtime on the Next.js documentation:
⚡️        https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes

 ERROR  Command failed with exit code 1: next-on-pages
```

I searched issues regarding this message, but only found in the context of Next.JS projects that uses "pages". My projects use only "app" directory. In "app" directory, I really don't have any knowledge about an "_error" page used in server-side. It seems that is not anything that is configured in the project.

The `error.js/ts` file that could be defined (which I tried) is just a client component. Even the `global-error.js/ts` being defined with "edge runtime" is not solving this error.

Unfortunately, checking the docs, I've found that some Next.JS features that I'm using in my project are not supported (at least yet, like ISR, some dynamic scenarios, etc), so I cannot use Cloudflare Pages for now. Hope this change in the future (or another simpler project could adopt Pages).

Thank you very much for the help. Hope any information that I gave could help somehow!

Best regards.

**Comment by tuahear** [comment]
@dario-piotrowicz Thanks for the demo repo it's really helpful! I finally got mine to work, after dealing with several problems. 

This might be useful to whomever came across, here's what I had to do additionally:
1. Disable experimental `outputFileTracingRoot` Nextjs config if you have it. (As described in https://nextjs.org/docs/pages/api-reference/next-config-js/output#caveats). Otherwise, you would see an error during vercel build that it can't locate a directory.
2. Remove libraries that's incompatible with edge runtime (might related to #384). Luckily most of them are my internal libraries in which I could refactor by myself.
3. Enable edge on non-static routes by putting `export const runtime = 'edge';`. Since I'm using `app` directory, I just lazily put it once at the root layout.tsx
4. I have several Nextjs projects in my monorepo and my goal is to deploy them all on Cloudflare Pages. Since it still only allows exactly 1 production branch and exactly 1 build configuration per Github repo, I had to tweak it a bit and here is how.
> 4.1 Enable preview branches (assuming preview deployments won't be automatically outdated and deleted 🤷).
> 4.2 Write a custom build script as suggested in https://developers.cloudflare.com/pages/how-to/build-commands-branches to trigger the right Nextjs project build based on branch name. Put the file in the root directory e.g., /build.sh
> 4.3 In the build command, after completed running `next-on-pages`, copy the output folder `.vercel` to wherever under the root directory (in my case `../../dist`).
> 4.4 Now setup your build configuration like this:
![Screenshot 2023-08-06 194222](https://github.com/cloudflare/next-on-pages/assets/5318909/f2c595c8-db0c-48f1-97bb-578b235e4456)

P.S. I just renamed this issue's topic to be something more relevant.

**Comment by dario-piotrowicz** [comment]
@luanmm , regarding the `_error` it can be generated if you have a `not-found` custom page as well (I'm not sure if it can also get generated in other scenarios as well)

Anyways I'm sorry to hear that next-on-pages doesn't support all you need, maybe we'll manage to get ISR at some point but it's tough 😓

Thanks a lot for trying the adaptor anyways, hopefully you'll be able to use it in some future projects 🙂

**Comment by dario-piotrowicz** [comment]
@tuahear I'm happy you manage to solve your various issues 😄 

And thanks for updating the issue's title 🙂, however issues to me are for tracking things that should or could be done and I feel like there isn't a clear action to take here, so I'd like to close this if ok, what would you say if we moved this to [discussions](https://github.com/cloudflare/next-on-pages/discussions) instead? (PS: I'm happy to do it or leave it up to you, whatever you prefer)

**Comment by tuahear** [comment]
Resolved. Thank you 🙏🏼
