### ISSUE TITLE
[🐛 Bug]: Cannot deploy large applications over 25MB

### ISSUE THREAD

**Issue by anonymouscatcher** [cloudflare/next-on-pages#330]
### next-on-pages environment related information

not relevant. 

### Description

I am currently trying to deploy my application on Cloudflare, but I am facing an issue due to the presence of over 30 routes and each function in my application, after being built, is approximately 1MB in size and the app size is more than 25MB. We  have a Pro/Business account, our request to increase the storage capacity has not received a response yet.
I think Cloudflare should make it easier to deploy large applications and at least there should be a difference between paid accounts and free accounts. I had discussion with staff on Discord and they made a ticket `PAGES-2748`. 

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks a lot for the issue @anonymouscatcher, sorry to hear you're having issues, I hope that the team will respond to you soon.

But regardless I think that an application should not easily get that large, that's definitely problematic, I'd like to understand if that's something caused by you or us and if something can be done regarding that.

What do you mean when you say that each function is 1MB? you mean the produced `func.js` files? that seems unreasonably big.

Do you have one such function that maybe you could share? (maybe one without business logic?) or more details to provide?

Are you using the latest package version by the way? (and not disabling the de-duplication of webpack chunks)

___

PS: I haven't yet tested next-on-pages on a large application, so there might be scaling issues that I'm unaware of 😕

**Comment by anonymouscatcher** [comment]
thanks for replying, Yes I meant `func.js` files 
I did some investigation it seems that what ever is in layout.js it will be shared between the nested routes and almost all functions sharing same code however we are using dynamic imports in our code not sure how dynamic imports are working on RSCs. 

If you want to have a look at functions I'd be happy to share the build files with you.

![image](https://github.com/cloudflare/next-on-pages/assets/53314423/e4b2dbee-df89-459c-8353-03a8adf4068f)

**Comment by adammartin1981** [comment]
> thanks for replying, Yes I meant `func.js` files I did some investigation it seems that what ever is in layout.js it will be shared between the nested routes and almost all functions sharing same code however we are using dynamic imports in our code not sure how dynamic imports are working on RSCs.
> 
> If you want to have a look at functions I'd be happy to share the build files with you.
> 
> ![image](https://github.com/cloudflare/next-on-pages/assets/53314423/e4b2dbee-df89-459c-8353-03a8adf4068f)

Bit random - but I don't suppose you can share how you were able to generate the `.func` files locally - or did you just run the cloudflare commands on your local machine?
