### ISSUE TITLE
[🐛 Bug]: Unable to find lambda for route: /robots.txt on Windows 10

### ISSUE THREAD

**Issue by alexeygorbachevskiy** [cloudflare/next-on-pages#346]
### next-on-pages environment related information

OS: Windows 10

Packages: 
"@cloudflare/next-on-pages": "1.1.1",
"vercel": "^30.2.3",
"next": "13.4.7"

Runtime: edge

### Description

Cannot make build via `npx @cloudflare/next-on-pages@1` locally. robots.txt located under app folder.
![image](https://github.com/cloudflare/next-on-pages/assets/37103509/76f52259-12e5-44b3-871e-e59020a34cdd)

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, it looks like you're running into a problem when the Vercel CLI tries to build your application, as indicated by the triangle at the start of the message. This is something that normally is out of our control 🙁.

As you are on Windows, it's possible that this is a bug due to their not so good Windows support. I have ran into issues like this before with the Vercel CLI on Windows.

My suggestion would be to try using something like Ubuntu through WSL2.

**Comment by dario-piotrowicz** [comment]
@alexeygorbachevskiy sorry you're having issues with building your application, as James mentioned this is something out of our control and as detailed in the error message in the screenshot you shared is something that should be checked with Vercel/Next.js itself.

I'm closing the issue as it's external to next-on-pages, I hope you don't mind 🙇
