### ISSUE TITLE
[🐛 Bug]: fails with default `_error` from page routes

### ISSUE THREAD

**Issue by eve0415** [cloudflare/next-on-pages#355]
### next-on-pages environment related information

Error on GitHub Actions. (Cannot test/reproduce as vercel has low support on Windows which I am using)

`@cloudflare/next-on-pages`: 1.2.0
`next`: 13.4.7

### Description

Fails with default `_error` from page routes.
I use app routers and no pages directory.
There shouldn't be an error with `_error` page (which is 404 as default).

### Pages Deployment Method

None

### Additional Information

```
⚡️ Completed `yarn dlx vercel build`.

⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
⚡️ 
⚡️ 	The following routes were not configured to run with the Edge Runtime:
⚡️ 	  - _error
⚡️ 
⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
⚡️ 	  export const runtime = 'edge';
⚡️ 
⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
```

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @eve0415 thanks a lot for the issue :slightly_smiling_face:

This is unfortunately a known issue which we're a bit blocked on: https://github.com/cloudflare/next-on-pages/issues/174

If Vercel were to update their implementation to honor the specified runtime that would fix this issue right away.

Until/if they don't do that we're not really able to do much about it (I thought of some workarounds at some point but anything we'd do/suggest would be pretty inconvenient/ugly) :sweat:

PS: I am not sure if they can change their implementation here, but even if they could, since the app routing is the suggested one I feel like they could not have enough incentive in fixing this in the pages routing anyways :sweat:

I'm closing this issue since it is a duplicated one, but please feel free to follow or post on #174 if you want
