### ISSUE TITLE
[⚡ Feature]: dynamically generated _routes.json for static assets

### ISSUE THREAD

**Issue by Yonom** [cloudflare/next-on-pages#388]
## Summary

I propose that the generated `_routes.json` excludes all static assets from pre-rendered static routes as well as the `public` directory.

I'm happy to contribute a PR to implement this and created this issue to  

a) confirm whether the proposed change is a good idea
b) understand the scope and requirements of the feature
c) identify the best way to implement the change

## Motivation

Preventing static paths from invoking a function decreases the costs of hosting Next.js sites on Cloudflare Pages.  
Currently, many of my Next.js apps seem more costly to run on Pages than on Vercel.  

## Current Behavior

The generated `_routes.json` always looks like this:

```json
{
  "version":1,
  "description":"Built with @cloudflare/next-on-pages@1.3.1.",
  "include":["/*"],
  "exclude":["/_next/static/*"]
}
```
[buildMetadataFiles.ts#L52](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts#L52)

## Desired Behavior

(The following are my test results using the /app Router)

For a very basic route `export default function HelloPage() { return <p>Hello!</p> }`, the following is generated:

<img width="126" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/1394504/119801a0-0026-45c8-9612-36eeef107c6f"><br /> 

A desirable `_routes.json` in this example would look like:

```json
{
  "version":1,
  "description":"Built with @cloudflare/next-on-pages@1.3.1.",
  "include":["/*"],
  "exclude":["/_next/static/*", "/hello", "/hello.rsc"]
}
```

### Step 1: identify which files to include

Files to include would be all prerendered routes, as well as files in the `public` directory.

This would basically include the following files from the `nop-build-log.json`:
- `prerenderFunctionFallbackFiles`
- `staticAssets`, but excluding:
  - /_next/static/* (already included via wildcard)
  - 404.html, 500.html (should be resolved by the function, as users would usually not literally navigate to /404 or /500)

#### Vercel config.json overrides

If an override is defined for the file in config.json, transform the filename based on that.

#### dropping .html file extension for prerenderFunctionFallbackFiles

For .html files, drop the .html file extension, as the original Next routed url did not include them either.

#### index.html support

`/index.html` is mapped to `/`

### Step 3: ensure no behavioral changes

We should only exclude paths if we can guarantee that no behavioral change is introduced via the exclude. The same file would be returned if one were to invoke the function.

For this, we can consult Vercel's `config.json`. The `routes` as well as `overrides` need to be checked.

#### routes

There are some routes which run before the file from filesystem is returned. These are routes in the "none" stage: [docs/technical/routing.md](https://github.com/cloudflare/next-on-pages/blob/main/docs/technical/routing.md)

For each route, we verify that it is side-effect free wrt the exclude clause being emitted. Otherwise, the exclude is dropped.

A route is considered side-effect free if:  

- The src regex does not match, OR
- the src regex does match, but we can analyze the rule to prove the behavior is not changed
  - example: all headers are already included via _headers (and no other alterations are being made)

#### overrides

If the path is part of overrides, the contentType should be honored.

### _routes.json limits

_routes.js only allows 100 include+exclude entries. For now, I would suggest dropping everything after the first 100 entries. In the future this can be optimized with a) a smarter prioritisation b) identifying wildcards which would not interfere with the routing

### trailing slash

Next.js ignores trailing slashes. This could be implemented through a default _redirect (something like `/*/ /:splat 200`?)

- [ ] is this something that needs two excludes in _routes.json?

### RSC requests

- [ ] Find a way to handle RSC requests

### Would you like to help?

- [X] Would you like to help implement this feature?

**Comment by Yonom** [comment]
## Blocker - RSC Headers

Every file is mapped to its corresponding .rsc file if an RSC header is present.

```json
{
  "src": "^/",
  "has": [
    {
      "type": "header",
      "key": "rsc"
    }
  ],
  "dest": "/index.rsc",
  "headers": {
    "vary": "RSC, Next-Router-State-Tree, Next-Router-Prefetch"
  },
  "continue": true,
  "override": true
},
{
  "src": "^/((?!.+\\.rsc).+?)(?:/)?$",
  "has": [
    {
      "type": "header",
      "key": "rsc"
    }
  ],
  "dest": "/$1.rsc",
  "headers": {
    "vary": "RSC, Next-Router-State-Tree, Next-Router-Prefetch"
  },
  "continue": true,
  "override": true
},
```

Not supporting this would limit the benefits of this feature to only files in `public` directory.

## Potential Solutions

Ideally, something we emit in `_redirects` can handle RSC headers.

### Solution 1 - Transform Rule

I could not find a way to filter requests with `RSC: 1` headers in Cloudflare.
However, it seems like RSC requests all have a `_rsc=` query parameter in addition to the `RSC: 1` header.

One could redirect these requests to the corresponding .rsc file with the help of Cloudflare Transform Rules.

<img width="1069" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/1394504/342989bc-ff2a-4997-8bd4-77bb5a608edb">

Furthermore, .rsc files need to have the correct header set (`text/x-component`). This can be emitted to `_headers`.

The downsides are that users must implement their own Cloudflare rule, as this won't be deployed inside pages. It also feels very hacky!

**Comment by james-elicx** [comment]
Hey there @Yonom,

I would like to start by apologizing as it seems like you have put a lot of effort into this issue, but to sum up my stance, I'm pretty opposed to excluding routes from invoking the routing system.

I'll start with a little bit of background. At the core of next-on-pages are two things; the build tool, and the routing system. The former ensures that things are in a format that can be deployed to Pages, while the latter ensures that incoming requests result in the correct response. In order to accomplish this, we have the worker that we generate that takes in a build output config and takes incoming requests through the different phases, rules, and conditions, that Vercel specifies should be followed for an incoming request to the Next.js app.

When looking at the routes that you consider to be static routes, they are not strictly static routes. In fact, they are only interpreted as such due to limitations with what we can deploy, not because of how we should deploy them. You see, routes that don't generate Edge functions will typically generate a Node.js Prerender function instead. This is a different type of function for the Vercel platform, and it is used for ISR. This means that incoming requests for those routes would normally interface with a cache to retrieve the prerendered file. If the revalidation period is up for that route, it would invoke the Prerender function in the background and deal with it as such, updating the prerendered file.

The sole reason we take the fallback prerendered files for these routes is so that we can deploy an application, it is not because of how these routes could be treated or that they should be interpreted as just being completely static.

What you are proposing is essentially an entirely new kind of routing system that should simulate different scenarios to determine all the possible ways a request to a path could be interpreted. It would then replace using a proper routing system for those routes and thereby significantly reduce the chance of ensuring the best attempt to replicate how incoming requests are treated by Vercel.

Requests are intended by Vercel to follow a routing system that uses the phases and rules specified in the build output config, as we currently do. Changing how certain routes are treated is treading on very thin ice and not something I would be comfortable with us shipping to people to deploy their apps with. We try to respect how Vercel intends for a deployed application to work, and changing this is pretty dangerous.

If people wish to exclude other assets/routes from invoking the worker, that should be entirely up to them, and them alone, and they should exercise extreme caution and not exclude routes. They are able to modify the `_routes.json` file if they desire. We should not be trying to mess with which routes invoke the worker, because this poses an incredibly high chance of leading to unexpected behaviour in an application. There are so many little edge cases that can pop up, so many little grey areas, and things that one might not expect. Not to mention to significant maintenance burden that it brings.

In your follow-up comment, you suggested using transform rules as a solution for routes that change depending on certain rules - this is unacceptable in my view. One of our key goals is to just work. We try our very best to ensure that things work out of the box with no extra effort or work from the user. If something requires an extra step to work, it is not really acceptable for us to include it - having to set the `nodejs_compat` compatibility flag is already too much to ask of people. There's also the point that those transform rules would only be for a domain and not `x.pages.dev`, and a user only gets 10 active transform rules on the free plan.

**Comment by Yonom** [comment]
Thanks a lot for the feedback!

To summarize:

- ISR routes are currently treated as static files, but future versions could support updating the prerendered file
- RSC headers can't be checked in _redirects; requiring a manual Transform Rule, which is too much to ask from users
- The transform rule potential solution does not work on `.pages.dev`, that is indeed a deal-breaker
- Without support for RSC headers, we're left with just the files in `public` directory
- There is a non-trivial amount of maintenance work and it's easy for bugs to be introduced

I agree with all points!

**Comment by Yonom** [comment]
The list of files that can be excluded currently ends up being pretty small, and the high complexity and maintenance required to implement such a feature correctly is not worth it. For my projects, I will override `_routes.json`. Closing this issue.

**Comment by pbshgthm** [comment]
Hey @Yonom , I'm running into the same issue you have mentioned here. Even though my entire app is static, every route is invoking the functions. How did you end up overriding the `_routes.json` ? Would be super helpful if you can point me at the right direction.

**Comment by Luzefiru** [comment]
Following up on this @Yonom. May I ask how your `_routes.json` looks like to match the `rsc` files? Thanks.

**Comment by divrawat** [comment]
> Hey @Yonom , I'm running into the same issue you have mentioned here. Even though my entire app is static, every route is invoking the functions. How did you end up overriding the `_routes.json` ? Would be super helpful if you can point me at the right direction.

have you found the solution to override the routes.json file ?
