### ISSUE TITLE
[🐛 Bug]: infinite re-build in watch mode

### ISSUE THREAD

**Issue by errmayank** [cloudflare/next-on-pages#400]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
	CPU: (8) arm64 Apple M1 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Binaries:
	Node: 18.17.0
	Yarn: 1.22.19
	npm: 9.6.7
	pnpm: 8.5.0
Package Manager Used: yarn (classic)
Relevant Packages:
	@cloudflare/next-on-pages: 1.3.1
	vercel: N/A
	next: N/A
```

### Description

Running next on pages in watch mode makes it go through infinite build cycle, it also adds vercel as a dev dependency automatically
```
"watch:cloudflare": "npx @cloudflare/next-on-pages@1.3.1 --watch",
```

These are all the scripts i have
```
"dev:wrangler": "wrangler pages dev .vercel/output/static --port=3000 --compatibility-flag=nodejs_compat --compatibility-date=2023-07-17",
"dev": "next dev",
"watch:cloudflare": "npx @cloudflare/next-on-pages@1.3.1 --watch",
"build": "next build",
"start": "next start",
"lint": "next lint",
"format": "prettier --write .",
```

It doesn't even wait on changes, just keep on re-building as soon as it finishes. I'm using next 13.4.12

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks for the issue @errmayank 🙂 

Regarding the vercel installation we do that on purpose:
https://github.com/cloudflare/next-on-pages/blob/671ff82c292ce29d8990a22b0c97c2e7ec990f24/packages/next-on-pages/src/buildApplication/buildVercelOutput.ts#L55
(introduced in PR #145)

We do it because yarn classic doesn't support dlx so I think that we can either install the dependency or error if not present (and between these two alternatives we chose the former)

___

Regarding the infinite loop I've opened PR #404 to fix it, if you want please try the [PR prerelease](https://github.com/cloudflare/next-on-pages/pull/404#issuecomment-1650278380) and let me know if that solves the issue for you 🙂

**Comment by errmayank** [comment]
Thank you very much. Tested it with pre-release, works fine now!
