### ISSUE TITLE
[🐛 Bug]: outdir argument is broken

### ISSUE THREAD

**Issue by guillaumelachaud** [cloudflare/next-on-pages#414]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Pro
        Memory: 32 GB
        Shell: /bin/zsh
Binaries:
        Node: 18.12.1
        Yarn: 1.22.19
        npm: 8.19.2
        pnpm: 8.6.7
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.4.0
        vercel: N/A
        next: 13.4.6

### Description

It looks like the outdir argument is currently broken. No matter the value passed, the CLI complains that it cannot parse it.

```
❯ npx @cloudflare/next-on-pages -o build

⚡️ Error parsing the outdir argument.
⚡️ Expected string, received null
```

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks for the issue @guillaumelachaud 🙂

The issue there is that you need to provide the argument by using `=`, as in: `-o=build`

That's not really intentional on our part, it's just a result of the library we use for parsing the cli arguments ([zodCli](https://github.com/GregBrimble/zodcli)).

The library does have some small issues like the one you mentioned and also doesn't generate a help message for us (so we currently [do that manually](https://github.com/cloudflare/next-on-pages/blob/3affd17441ad5754c089cbd9c10adae97a09e7d8/packages/next-on-pages/src/cli.ts#L140) 😓). 

Since the library is, as far as I know, not being worked on anymore (meaning that the above things won't likely improve) we should switch to a different one, that will solve your issue + the help message one + potential others.

Since you have checked that you'd like to help fixing the issue, if you'd want, you're totally welcome to explore using a different library (I would probably suggest [commander](https://www.npmjs.com/package/commander)) for parsing the arguments 🙂 

Let me know if you'd like to give it a go! 🙂
(Otherwise I'll look into this at some point soon (but it's not a huge priority))

**Comment by guillaumelachaud** [comment]
> The issue there is that you need to provide the argument by using =, as in: -o=build

Got it, makes sense. It might need better documentation to make it clear though. But ultimately, as you mention, if zod is deprecated and commander is the replacement of choice, then no need to update the doc, it can wait for the switch.

Not a huge priority indeed, I might have some bandwidth to look into it this week-end or the one after.

**Comment by dario-piotrowicz** [comment]
yeah I totally agree it needed to be better documented, but anyways forcing the `=` was never going to be ok as the final solution (I was expecting zodCli to fix that on their end)

anyways yeah it's going to be fixed soon

I'm assigning the issue to you, anyways please don't feel pressured to fix it if you don't have the time, if you're too busy I don't mind taking it on (it's something I've been planning to do for a bit anyways, but as I said it hasn't been a huge priority)
