### ISSUE TITLE
"ERROR: Could not map all functions to an entry in the manifest." when adding basePath to next.config.js

### ISSUE THREAD

**Issue by kendall-wahnschaffe** [cloudflare/next-on-pages#42]
### Out of the box, everything works
✅ Works as expected
Following steps 1 - 4 from the (README)[https://github.com/cloudflare/next-on-pages#quick-start]

✅ Works as expected
`npx @cloudflare/next-on-pages --experimental-minify`

✅ Deploys as expected
`npx wrangler pages publish .vercel/output/static/`

### However, with basePath
Add `basePath` to `next.config.js`

```js
const nextConfig = {
  basePath: "/base-path",
  experimental: {
    runtime: "experimental-edge",
  },
  reactStrictMode: true,
};
```
❌ Does not work.
`npx @cloudflare/next-on-pages --experimental-minify`

Build completes, but logs the following ERROR:

```ERROR: Could not map all functions to an entry in the manifest.```

Furthermore, if I proceed to deploy the application, I get a browser HTTP ERROR 404 at `/base-path` and the application's 404 page at `/base-path/`

**Comment by hanford** [comment]
This happens to me as well. I rely on `basePath` pretty heavily in order to have many Next.js applications on the same hostname.

I've created a repro over here: https://github.com/hanford/next-on-pages-42 and can also be messaged on the Cloudflare Discord as @hanford if any additional information is helpful

**Comment by hanford** [comment]
I believe https://github.com/cloudflare/next-on-pages/pull/44 should add proper support for `basePath` on `next-on-pages`. I've got the changes in the PR available in `.patch` that can be applied using something like [patch-package](https://www.npmjs.com/package/patch-package)

The patch file is here: https://gist.github.com/hanford/9308f35b5d12a3c225a0045cf6bff3c8

(unrelated, also in the patch, I've disabled the `prepInstall` function because I've been using Pages direct upload and `next-on-pages` doesn't yet support many package managers (https://github.com/cloudflare/next-on-pages/pull/11), if desired I can create a new patch without that change..

**Comment by rationalthug** [comment]
Will this fix be accepted in the near future? I utilize basePath extensively as well and am using Pages' GitHub integration, which causes the build to fail with this same error.
