### ISSUE TITLE
[🐛 Bug]: Sentry integration

### ISSUE THREAD

**Issue by martwozniak** [cloudflare/next-on-pages#421]
### next-on-pages environment related information

System:
        Platform: win32
        Arch: x64
        Version: Windows 11 Pro
        CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
        Memory: 32 GB
        Shell: C:\Program Files\Git\usr\bin\bash.exe
Binaries:
        Node: 20.5.0
        Bun: N/A
        pnpm: N/A
        Yarn: 1.22.19
        npm: 9.8.0
Package Manager Used: yarn (classic)
Relevant Packages:
        @cloudflare/next-on-pages: 1.5.0
        vercel: N/A
        next: N/A

### Description

Sentry does not work when published on Cloudflare Pages. 

functions/_middleware.ts

```
import sentryPlugin from '@cloudflare/pages-plugin-sentry';
import { PagesFunction } from '@cloudflare/workers-types';

export const onRequest: PagesFunction = sentryPlugin({
  dsn: 'dsn_here',
});
```

### Reproduction

1. Create nextjs project
2. npx @sentry/wizard@latest -i nextjs
3. Publish to cloudflare pages 
4. Sentry not logging any errors
5. Add middleware
```
import sentryPlugin from '@cloudflare/pages-plugin-sentry';
import { PagesFunction } from '@cloudflare/workers-types';

export const onRequest: PagesFunction = sentryPlugin({
  dsn: 'dsn_here',
});
```
7. Sentry not logging any errors

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

71596039

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks for the issue @martwozniak 🙂 

The issue here is that `@cloudflare/next-on-pages` generates a Pages project in [advanced mode](https://developers.cloudflare.com/pages/platform/functions/advanced-mode/), this mode is incompatible with the `functions/` directory implementation and the latter gets ignored, as you can see in the docs:
![Screenshot 2023-08-25 at 21 23 27](https://github.com/cloudflare/next-on-pages/assets/61631103/edd5876c-5bea-4351-b14a-545c59b6a880)

So it is expected for your implementation not to work, you'll need to change it so that you integrate sentry directly in your Next.js application.

I haven't used sentry before so unfortunately I cannot help you much in that regard, but the [sentry docs](https://docs.sentry.io/platforms/javascript/guides/nextjs/) seem to include clear instructions on how to do so 🙂 

Also note that people have had a few issues with sentry (like https://github.com/cloudflare/next-on-pages/discussions/178 and https://github.com/cloudflare/next-on-pages/issues/420), so I can't guarantee that it'll work for your specific use case (but I'll be here to help if I can 🙂)

I hope this is helpful 🙂
