### ISSUE TITLE
Investigate impact of new `process` object in nodejs_compat

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#452]
Does this change how we're substituting in `process.env` in this project at all?

https://developers.cloudflare.com/workers/runtime-apis/nodejs/process

**Comment by dario-piotrowicz** [comment]
As we discussed it doesn't look like Cloudflare's runtime `process.env` can be of much use to us (fortunately it also doesn't have any negative impact)

___

Also as we discussed, later we could potentially use it if we were to use `process.env` for text bindings only (instead of setting the bindings there as we currently do), anyways we can't stop adding the bindings to our global `process.env` proxy in patch/minor versions so this will have to wait for the next next-on-pages major version in any case

**Comment by dario-piotrowicz** [comment]
I'm looking into doing a major bump right now, so that made me circle back to this issue

As discussed above the Cloudflare's runtime `process.env` doesn't seem to be too helpful to us, besides that we've been also relying on `process.env` in the `next-dev` sub-module so I do think that moving away from it right now anyways would introduce more complications than anything else

So I'm closing this issue as I don't think that the new `process` object has much baring in next-on-pages nor it should drive any future decision regarding whether we want to move away from `process.env`

I hope this is fine, please let me know if you disagree @GregBrimble 🙂
