### ISSUE TITLE
is it possible to get geolocation in next api, like workers

### ISSUE THREAD

**Issue by hanumanjiblog** [cloudflare/next-on-pages#46]
is it possible to get geolocation in next api, like workers

**Comment by kingrupam** [comment]
@GregBrimble any update

**Comment by GregBrimble** [comment]
Hi! Have you tried accessing the `request.cf` object? Does that contain the information you're looking for?

https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties

**Comment by hanumanjiblog** [comment]
@GregBrimble not working on NextJs

**Comment by dario-piotrowicz** [comment]
Yeah it looks like Next manipulates the request object ([here](https://github.com/vercel/next.js/blob/e6f33ec3a1513e242767d8ada3757f2beb747290/packages/next/src/server/web/adapter.ts#L96C29-L107) I think)

So I think we should take the info from the `cf` object and moved it to `geo` so that next recognizes it.

(Eventually I think we need to export `env`, `ctx` and `cf` to the user somehow in any case, but Next apps can indeed rely on `geo` I'd imagine so the above should be done regardless I think)

**Comment by nicholasfulton** [comment]
> Yeah it looks like Next manipulates the request object ([here](https://github.com/vercel/next.js/blob/e6f33ec3a1513e242767d8ada3757f2beb747290/packages/next/src/server/web/adapter.ts#L96C29-L107) I think)
> 
> So I think we should take the info from the `cf` object and moved around so that next recognizes it.
> 
> (Eventually I think we need to export `env`, `ctx` and `cf` to the user somehow in any case, but Next apps can indeed rely on `geo` I'd imagine so the above should be done regardless I think)

Is there any progress on exporting `cf` to Next.js? My team needs this feature for routing to the nearest available AWS region for DynamoDB. The `request.cf.colo` property seems like the best strategy for that, and I haven't been able to figure out a way of mapping the fields as headers so far.
