### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by szymondlugolecki** [cloudflare/next-on-pages#52]
When trying to run `npx @cloudflare/next-on-pages` I get an error

```
C:\Users\...\...\project>npx @cloudflare/next-on-pages  
@cloudflare/next-to-pages CLI
⚡️
⚡️ Installing 'vercel' CLI...
⚡️
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '-D', 'vercel' ]
}
```

I use
node@16.13.0 and @18.12.0
npm@8.1.0

**Comment by LOLBRUHNICE** [comment]
I have already created a pr that can fix this issue, waiting for merge, ref https://github.com/cloudflare/next-on-pages/pull/34

**Comment by fineshop** [comment]
How can we fix this issue on windows?

**Comment by gvatsov** [comment]
> How can we fix this issue on windows?

I can say that using the @LOLBRUHNICE changes from the quoted PR are working for me on Windows 11.

**Comment by surjithctly** [comment]
FYI: I'm still getting same error. Looks like its not fixed. Using latest version. cc: @LOLBRUHNICE @dario-piotrowicz 

<img width="1229" alt="CleanShot 2023-03-22 at 21 32 26@2x" src="https://user-images.githubusercontent.com/1884712/226965930-30e6293a-e111-4616-94dd-1d3320edf01e.png">

**Comment by dario-piotrowicz** [comment]
Hi @surjithctly are you using `pnpm`?

if so can you delete all `pnpm` files and try again (just using `npx`)?

Are you on windows?

**Comment by surjithctly** [comment]
Yes. I’m using PNPM.

This issue occurs on cloudflare pages build (not local). I’m on Mac.

**Comment by dario-piotrowicz** [comment]
@surjithctly I've just tried with a fresh new Next.js app ([repo](https://github.com/dario-piotrowicz/pnpm-next-on-pages-test))

I think there are two possible solutions:
 - remove the `pnpm-lock.yaml` file (if you want to keep using pnpm locally you could add the file to the gitignore although I don't think it's the best) ([f695cc](https://github.com/dario-piotrowicz/pnpm-next-on-pages-test/commit/f695cc716cb4ff9dee5f1f3fdc3741d35cbb2325))
 - add pnpm as a devDependency (so that the cloudflare builder can find it when needed) ([b1ad7a](https://github.com/dario-piotrowicz/pnpm-next-on-pages-test/commit/b1ad7a86cbf4e0e6e03654a1a0d1b32cb2aea206))
 (I guess you could also try to change the build command in the dashboard so that it installs pnpm for you as well, I haven't tried that but I think it should work)
 
 Is any of this helpful? :slightly_smiling_face:

**Comment by surjithctly** [comment]
Thanks @dario-piotrowicz adding `pnpm` as devDep worked. 

But I guess this issue should be opened again, because this app should work without that as well.
