### ISSUE TITLE
[🐛 Bug]: ESLint rule no-app-not-found-runtime is exported as no-app-not-found

### ISSUE THREAD

**Issue by mattiasw** [cloudflare/next-on-pages#530]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Package Manager Used: npm (10.1.0)

Relevant Packages:
	@cloudflare/next-on-pages: 1.7.2
	vercel: N/A
	next: N/A
```

### Description

The ESLint rule that is called `no-app-not-found-runtime` in the documentation is exported as `no-app-not-found`.

### Reproduction

1. Install the ESLint plugin and make sure the rule `next-on-pages/no-app-not-found-runtime` is set.
2. Add `export const runtime = 'edge';` to the `not-found.tsx` page.
3. Run linting.

No error. But if changing the name to `next-on-pages/no-app-not-found` it works.

### Pages Deployment Method

None

### Additional Information

I can make a PR if you tell me whether it's best to change the documentation or to change the export.

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
ah... yeah you're totally right! 😓 

https://github.com/cloudflare/next-on-pages/blob/bf57ec9d01b354ea6c9b9bd17c683d592d5c6ae9/packages/eslint-plugin-next-on-pages/src/index.ts#L11

https://github.com/cloudflare/next-on-pages/blob/bf57ec9d01b354ea6c9b9bd17c683d592d5c6ae9/packages/eslint-plugin-next-on-pages/src/index.ts#L17

That's my bad, I think that the two lines above are the only places that need this changed, since you ticket that you'd like to help fixing this bug, please let me know if you want to apply the changes or if I should 🙂 

(PS: updating this is technically a breaking change... but I think it could be added as a patch since the rule name is actually wrong (and the docs do indicate it with the correct name) 🤔)

**Comment by mattiasw** [comment]
I can do it. I was also wondering if this would be considered a breaking change or not. But I'm with you, the documented API will not change, it will just start working. :-)
