### ISSUE TITLE
[🐛 Bug]: ESLint rule no-app-not-found-runtime does not work when using a src folder

### ISSUE THREAD

**Issue by mattiasw** [cloudflare/next-on-pages#531]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Package Manager Used: npm (10.1.0)

Relevant Packages:
	@cloudflare/next-on-pages: 1.7.2
	vercel: N/A
	next: N/A
```

### Description

When using a `src` folder at the top level of the application, the rule `no-app-not-found-runtime` does not match the file `src/app/not-found.tsx` and therefore does not show any errors.

### Reproduction

1. Create a Next.js project with this structure:
```
src/
  app/
     not-found.tsx
```
2. Run linting with the rule `no-app-not-found-runtime` active (currently it's exported as `no-app-not-found`, see other issue: #530)

### Pages Deployment Method

None

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks a lot for the issue @mattiasw 😃

Yeah you're again right, I think that this can be very simply fixed by updating accordingly this regex:
https://github.com/cloudflare/next-on-pages/blob/bf57ec9d01b354ea6c9b9bd17c683d592d5c6ae9/packages/eslint-plugin-next-on-pages/src/rules/no-app-not-found-runtime.ts#L6

Again I am happy to fix this or let you apply the change if you'd like to 😃 , please let me know what you prefer 🙏

**Comment by mattiasw** [comment]
I can do this one too.
