### ISSUE TITLE
[🐛 Bug]: ESLint rule no-unsupported-configs does not support config files with extension .mjs

### ISSUE THREAD

**Issue by mattiasw** [cloudflare/next-on-pages#532]
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Package Manager Used: npm (10.1.0)

Relevant Packages:
	@cloudflare/next-on-pages: 1.7.2
	vercel: N/A
	next: N/A

### Description

ESLint rule `no-unsupported-configs` does not support config files with extension `.mjs`. Looking at the implementation it's going to have the same issue with the `.cjs` extension.

### Reproduction

1. Use ES module syntax in your Next.js config file and name it `next.config.mjs`.
2. Use a config value that is not allowed, e.g. `compress: true`.
3. Run linting.

It should report the error but it doesn't.

### Pages Deployment Method

None

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks a lot again for raising the issues with the eslint plugin package 😄

Again let me know if you want to take this on and I'll assign it to you, otherwise I can look into it at some point 🙂 

Besides that I don't have much else to add as updating this doesn't really look like a trivial change (it doesn't look too too complex either but it would involve a bit of refactoring and whatnot)

**Comment by mattiasw** [comment]
@dario-piotrowicz PR created. Seemed simple though, so please tell me if I missed something.
