### ISSUE TITLE
[🐛 Bug]: redirects from the next.config.js file not working. 

### ISSUE THREAD

**Issue by bigansh** [cloudflare/next-on-pages#577]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
        CPU: (8) arm64 Apple M1 Pro
        Memory: 16 GB
        Shell: /usr/local/bin/pwsh
Binaries:
        Node: 18.0.0
        Bun: N/A
        pnpm: 6.11.0
        Yarn: 1.22.15
        npm: 8.6.0
Package Manager Used: yarn (classic)
Relevant Packages:
        @cloudflare/next-on-pages: 1.5.0
        vercel: N/A
        next: N/A

### Description

I have a set of redirects that i have added in my `next.config.js` file which don't seem to work when deployed to Cloudflare Pages. It works on the localhost but the deployed version throws the 404 page. We even tried to clear all the cache but didn't result in any changes. Please help me get this sorted. 

Details:
NextJS: 13.4.7
next-on-pages: 1.3.0

Demo
![CleanShot 2023-12-08 at 10 51 46](https://github.com/cloudflare/next-on-pages/assets/53395243/d816922d-b406-485b-be78-5a889648879b)

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

https://abb91484.mygptbrain.pages.dev/

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @bigansh, thanks for the issue 🙂

I am pretty sure that standard `next.config.js` redirects do work with `@cloudflare/next-on-pages` as we do have [tests to make sure they do](https://github.com/cloudflare/next-on-pages/blob/main/pages-e2e/features/pagesConfigsRewritesRedirectsHeaders/redirects.test.ts). I've also double checked myself and seen no issue with the redirects.

So I am not sure what might be going wrong with your application, but there are a few things that come in mind:

- I am not sure what version of `@cloudflare/next-on-pages` you are using, since you mentioned both `1.3.0` and `1.5.0`, but in either case I would suggest you to try with the latest (which is [`1.8.2`](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.8.2))
- what do you mean by  `It works on the localhost`? by running `next dev`? have you tried building the application and running it with `wrangler pages dev .vercel/output/static --compatibility-flag nodejs_compat`? do the redirects work in that case?
- do you by any chance have a custom [`_routes.json` file](https://developers.cloudflare.com/pages/platform/functions/routing/#create-a-_routesjson-file) that might be causing the problem?

**Comment by bigansh** [comment]
hey, i updated my next-on-pages and it started working. thank you.

**Comment by dario-piotrowicz** [comment]
Awesome! I'm glad to hear that 😄
