### ISSUE TITLE
[🐛 Bug]: Workers can slow down based on dependencies from other/unused routes

### ISSUE THREAD

**Issue by juanferreras** [cloudflare/next-on-pages#722]
### next-on-pages environment related information

```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
        CPU: (8) arm64 Apple M1 Pro
        Memory: 16 GB
        Shell: /bin/zsh
Package Manager Used: npm (9.8.1)

Relevant Packages:
        @cloudflare/next-on-pages: 1.11.0
        vercel: 33.6.1
        next: 14.1.0
```

### Description

It seems that despite the [lazy-loading strategy](https://github.com/cloudflare/next-on-pages/blob/main/docs/technical/lazy-loading.md), if any route has a large dependency tree, it can ultimately slow down the `_worker.js/index.js` entrypoint altogether for other routes.

I've first replicated on a real/complex setup where we're reading from KV inside middleware. It was surprising there to see that if the Worker wasn't re-using an existing isolate, even KV cache hits could take XXXms of processing instead of YYms. Then we managed to confirm that the time was attributed to the KV await but in reality was spent before (e.g. in some form of worker/script startup that we can't really measure) and just attributed to the first I/O await operation in the worker.

I've built a simple reproduction without KV as we can measure the delay simply looking at TTFB on the response. With the reproduction example below, ~100ms of TTFB can be added and measured with confidence when comparing a single unused route having a lot of dependencies vs not including that page in the deploy.
![CleanShot 2024-03-25 at 16 27 15@2x](https://github.com/cloudflare/next-on-pages/assets/8507996/8d2d6cbf-b332-470e-8b8b-f2075dc65cd8)
- [comparison](https://www.webpagetest.org/graph_page_data.php?tests=240325_AiDcWY_ES1%2C240325_BiDcMT_EMS&medianMetric=TTFB&fv=1&median_run=1&control=0), [without large-page](https://www.webpagetest.org/result/240325_AiDcWY_ES1/?test=240325_AiDcWY_ES1&medianMetric=TTFB), [with large-page](https://www.webpagetest.org/result/240325_BiDcMT_EMS/?test=240325_BiDcMT_EMS&medianMetric=TTFB)

### Reproduction

Please see https://github.com/juanferreras/next-cold-start. It's a next pages router with 2 routes (/ and /large-page), but middleware always returning the response.

1. Clone it
2. Deploy it as-is, use WebPageTest or any tool to measure TTFB (note reutilization of isolates can mask the issue)
3. Move/delete large-page so it isn't included in the build
4. Deploy again, use WebPageTest or any tool to measure TTFB

**Expected result:** unless I'm wrong, there shouldn't really be any measurable difference except when executing the large route itself as we aren't really compiling/parsing/executing its dependencies.

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

next-cold-start

### Additional Information

I've benchmarked things inside `next-on-pages` and I couldn't find the culprit. I've tried `--no-build` (from an recently merged PR in `workers-sdk` which fixed it for `workerJsDir`) and it didn't seem to change either (e.g. that seems to govern only the first-party code of `next-on-pages`, but either way the additional modules seem to be uploaded as different files).

Is this running into any implementation detail at the infrastructure level (e.g. cold starts requiring time to move modules over)? Is it something rather binary, once a worker needs more than >1MB gzipped, or something that will continue worsening metrics until the 10MB gzipped cap? (I can tweak the reproduction to reflect this but I'm quite confidently leaning towards the latter, the more code in any route, the slower all become)

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks so very much for such a comprehensive and well studied issue @juanferreras! ❤️ 

As you said the lazy loading strategy should make next-on-pages apps as performant as possible, so my gut feeling on this is that this is a technical limitation of the Cloudflare network as maybe pulling the user code adds such cold start delays...

But I'll have to investigate this (hopefully I'm wrong as I'd love it if we could this 🙂).

I've checked your reproduction and its output and it looks to me like there is not obvious fault of next-on-pages 😕 

What I want to do next, is to actually create a minimal reproduction using Pages with a plain `_worker.js` directory and lazy loading and see if we can recreate this there, that should make it clear at least if the issue is actually related to next-on-pages or not and we can then take it from there and see how to best proceed (having such a minimal repro should also make it easier to trace the thing internally and share it with other teams if need be).

I'll do that in the next few days and I'll let you know how it goes 🙂, but if you do have extra cycles and would actually like to look into that please feel free 😄

**Comment by juanferreras** [comment]
We've discussed with @dario-piotrowicz and we've confirmed this issue is not related to `next-on-pages` code specifically. 

I've conducted further tests based on his much-appreciated insights and I'm moving the issue over to https://github.com/cloudflare/workers-sdk/issues/5415 

Thanks!
