### ISSUE TITLE
[🐛 Bug]: waitUntil has this binding on ctx, CHANGELOG example is broken

### ISSUE THREAD

**Issue by sleexyz** [cloudflare/next-on-pages#732]
### Description

The [CHANGELOG](https://github.com/cloudflare/next-on-pages/blob/a84add8db159a7c5d728c8169ef7b5aeac768e29/packages/next-on-pages/CHANGELOG.md#minor-changes-1) has an example of destructuring `waitUntil` from `ctx`.

But this isn't actually supported. I spent 3 hours pulling my hair out trying to understand why my local preview and cloud previews were broken and then I stumbled upon on this post: https://www.answeroverflow.com/m/1131117840112549918

calling `ctx.waitUntil` without the destructure fixes the issue.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @sleexyz thanks for the issue :slightly_smiling_face: and sorry for the very late reply :bow: 

You're right that destructuring the functions from the `ctx` object doesn't seem to work, it was a mistake on my part to include that in the changelog, sorry for the confusion :bow: 

I've created this repo: https://github.com/dario-piotrowicz/workerd-ctx-destructuring-reproduction which I'll share with the workerd team to understand if this behavior can be fixed or if it is intentional/to stay.

In the case of the latter, I'll have to make sure to replicate this behavior in the `next-dev` submodule (since currently with `next dev` the destructuring  does work) and also update [our documentation](https://developers.cloudflare.com/workers/runtime-apis/context) to include a warning regarding this behavior (which can indeed surprise developers).

**Comment by dario-piotrowicz** [comment]
Updating `getPlatformProxy` (which is used under the hood by `next-dev`) so that it replicates the same behavior during local development: https://github.com/cloudflare/workers-sdk/pull/6199
