### ISSUE TITLE
[⚡ Feature]: ESLint Flat Config Support

### ISSUE THREAD

**Issue by sushi-chaaaan** [cloudflare/next-on-pages#755]
### Description

ESLint version 9 has also been released and it is better to support Flat Config.

### Would you like to help?

- [X] Would you like to help implement this feature?

**Comment by austinm911** [comment]
Yes please!

**Comment by dario-piotrowicz** [comment]
Hi @sushi-chaaaan, thanks for the issue 🙂 (and sorry for the late reply 🙇)

The support for flat config files and Eslint 9 needs to be implemented in Next.js itself, I can see that they do already have an issue regarding this: https://github.com/vercel/next.js/issues/64453

As for next-on-pages we do not have anything here that prevents the use of flat config files and I am pretty sure our eslint plugin should just work with them.

So I would recommend you to follow the Next.js issue above and comment there or even open a PR in their repo if you're up for it. Once eslint 9 and flat config files are supported by Next.js everything here should work too (and if not please feel free to open a new issue here regarding the new potential problems).

If it's ok by you I'll close this issue since there isn't really anything for us to do here regarding this, but if you disagree please let me know and feel free to reopen it 🙂
