### ISSUE TITLE
Next/Images does not work properly

### ISSUE THREAD

**Issue by chand1012** [cloudflare/next-on-pages#94]
When I use Next's Images component, even with Next On Pages, the image will not load and instead returns a 404 due to a missing endpoint. 
![image](https://user-images.githubusercontent.com/3521582/224373464-636edb93-f39a-4ca1-a155-276994ba6bfb.png)
It works when developing locally which is a bit annoying since I didn't find the issue until after I pushed to my Pages site.

**Comment by dario-piotrowicz** [comment]
Hi @chand1012 sorry to hear that you only saw that after pushing the site 😓 

I think it's already covered in the README that the package does not yet support next images: https://github.com/cloudflare/next-on-pages#build-output-configuration

**Comment by james-elicx** [comment]
> Oops, must have missed that. Since this feature will probably never be fully supported as standard NextJS does, would there be a way to add a polyfill or something similar so that when the website is built using next-on-pages the `<Image />` tags would get replaced by standard `<img />` tags? It would make migration to Cloudflare Pages easier for existing sites.

I just want to point out that you could try using a custom loader for `next/image` so that you aren't relying on the default Next.js image optimization API, like in the [example](https://developers.cloudflare.com/images/image-resizing/integration-with-frameworks/#nextjs) for Cloudflare Image Optimization.

The Next.js config actually [allows](https://nextjs.org/docs/api-reference/next.config.js/custom-image-loader-config) you to specify the loader in there so you don't have to modify any of your existing `<Image />` components.
